name: Deploy docs

on:
  push:
    paths:
    - 'docs/**/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      #with:
        #node-version: '12.x'
    - name: Deploy docs
      working-directory: docs
      run: |
        npm i
        npm run deploy
